name: "current_wf"
description: "索引當前目錄的文件"
author: "BMad"

config_source: "{project-root}/bmad/mhp/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/workflows/current_wf"
template: false
instructions: "{installed_path}/instructions.md"

default_output_file: "{output_folder}/current_wf-report-{{date}}.md"

standalone: true