name: "hackathon-kickoff"
description: "引導團隊進行問題定義、初步腦力激盪、設計思考、團隊角色分配和專案規劃。"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/mhp/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/mhp/workflows/hackathon-kickoff"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/hackathon-kickoff-report-{{date}}.md"

# Invocation control
standalone: true
