name: "hackathon-retrospective"
description: "引導團隊回顧黑客松過程，總結經驗教訓，規劃未來改進。"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/mhp/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/mhp/workflows/hackathon-retrospective"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/hackathon-retrospective-report-{{date}}.md"

# Invocation control
standalone: true
