name: "solution-development"
description: "指導團隊進行迭代開發，包括設計、實現、測試和優化。"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/mhp/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/mhp/workflows/solution-development"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/solution-development-report-{{date}}.md"

# Invocation control
standalone: true
